export const adminSideBarData = [
	{ title: "Users", content: ["Admins", "Editors", "Instructors", "Students"] },
	{ title: "Articles", content: ["Published Articles", "Scheduled Articles", "Saved Drafts"] },
	{ title: "Jobs", content: ["Published Jobs", "Saved Drafts"] },
	{ title: "Courses", content: ["Published Courses", "Scheduled Courses", "Saved Drafts"] },
];

export const adminJobsListData = [
	{
		company: "Here's the company name",
		position: "Here's the position",
		status: "Open",
		postedDay: "Monday",
		postedDate: "June 5th",
		postedTime: "12:30 PM",
		applications: 27,
		field: "IT & Technology",
	},
	{
		company: "Here's the company name",
		position: "Here's the position",
		status: "Open",
		postedDay: "Monday",
		postedDate: "June 5th",
		postedTime: "12:30 PM",
		applications: 8,
		field: "IT & Technology",
	},
	{
		company: "Here's the company name",
		position: "Here's the position",
		status: "close",
		postedDay: "Monday",
		postedDate: "June 5th",
		postedTime: "12:30 PM",
		applications: 15,
		field: "IT & Technology",
	},

	{
		company: "Here's the company name",
		position: "Here's the position",
		status: "close",
		postedDay: "Monday",
		postedDate: "June 5th",
		postedTime: "12:30 PM",
		applications: 32,
		field: "IT & Technology",
	},
	{
		company: "Here's the company name",
		position: "Here's the position",
		status: "close",
		postedDay: "Monday",
		postedDate: "June 5th",
		postedTime: "12:30 PM",
		applications: 6,
		field: "IT & Technology",
	},
	{
		company: "Here's the company name",
		position: "Here's the position",
		status: "close",
		postedDay: "Monday",
		postedDate: "June 5th",
		postedTime: "12:30 PM",
		applications: 3,
		field: "IT & Technology",
	},
];

